GET http://localhost:3001/api/blogs/

###

POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "kristinatodorova",
    "password": "musaka"
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtyaXN0aW5hdG9kb3JvdmEiLCJpZCI6IjY3YmIxZTliY2M4ZmUwYWQ2NzQ1YzgzMyIsImlhdCI6MTc0MDc2NTY1NX0.ycbnZq2q4nN7yZvo21olttRh2X5w5otMCv4uwiVz53o


{
    "title": "How to be a fullstack rockstar",
    "author": "Kristina Todorova",
    "url": "google.com",
    "likes": "10",
    "userId": "67bb1e9bcc8fe0ad6745c833"
}

###
DELETE http://localhost:3001/api/blogs/67c1edc915dc861e7bb116fe
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtyaXN0aW5hdG9kb3JvdmEiLCJpZCI6IjY3YmIxZTliY2M4ZmUwYWQ2NzQ1YzgzMyIsImlhdCI6MTc0MDc2NTc3MH0.9LyOx01RWgEe9T5IDE9-83tdvOMMkmMyRZa0Y_wyagI

###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtyaXN0aW5hdG9kb3JvdmEiLCJpZCI6IjY3YmIxZTliY2M4ZmUwYWQ2NzQ1YzgzMyIsImlhdCI6MTc0MDc2MjY3OX0.4dOdeo9UOKzHnNd860SCzu8FJJ8WYU2M916TCGTyTL4


{
    "title": "How to be a marketing rockstar",
    "author": "Koko",
    "url": "google.com",
    "likes": "10000"
}

###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtyaXN0aW5hdG9kb3JvdmEiLCJpZCI6IjY3YmIxZTliY2M4ZmUwYWQ2NzQ1YzgzMyIsImlhdCI6MTc0MDc2MjY3OX0.4dOdeo9UOKzHnNd860SCzu8FJJ8WYU2M916TCGTyTL4


{
    "title": "How to refactor an app and not f- it up",
    "author": "Kristina Todorova",
    "url": "google.com",
    "likes": "1",
    "userId": "67bb1e77cc8fe0ad6745c831"
}